behaviors:
  UnlimitedCapacity:
    trainer_type: poca
    hyperparameters:
      batch_size: 512
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 1024
      num_layers: 3
      vis_encode_type: simple
      memory:
        memory_size: 128
        sequence_length: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 200
    checkpoint_interval: 100000
    max_steps: 50000000
    time_horizon: 256
    summary_freq: 60000
